/**
 * Phase 1 Unit Tests: Context IR Multi-Resolution Tiers & Source Provenance Engine
 */

import { ContextIRGenerator, ContextEntity } from '../src/solver/contextIR';
import { SourceProvenanceEngine } from '../src/workspace/provenance';

export function runContextIRTests(): boolean {
    console.log('\n--- Running Phase 1 Context IR & Source Provenance Tests ---');

    // 1. Test Context IR Multi-Resolution Tiers
    const generator = new ContextIRGenerator();

    const sampleEntity: ContextEntity = {
        id: 'auth_service_entity',
        filePath: 'src/services/authService.ts',
        symbolName: 'AuthService',
        kind: 'class',
        baseUtility: 100,
        docstring: '/** Authenticates users and generates JWT sessions */',
        signatures: [
            'export class AuthService {',
            '  public async login(user: string, pass: string): Promise<UserSession>;',
            '  public async validateToken(token: string): Promise<boolean>;',
            '}'
        ],
        calleeStubs: ['DatabasePool.query()', 'CryptoEngine.hashPassword()'],
        slicedCode: 'export class AuthService {\n  public async login(user: string, pass: string): Promise<UserSession> {\n    return this.db.find(user);\n  }\n}',
        fullCode: 'export class AuthService {\n  private db = new Database();\n  public async login(user: string, pass: string): Promise<UserSession> {\n    console.log("login start");\n    for (let i = 0; i < 50; i++) { /* hashing */ }\n    return this.db.find(user);\n  }\n  public async validateToken(token: string): Promise<boolean> {\n    return true;\n  }\n}'
    };

    const resolutions = generator.generateAllResolutions(sampleEntity);

    const rEx = resolutions.get('R_exclude')!;
    const r0 = resolutions.get('R0')!;
    const r1 = resolutions.get('R1')!;
    const r2 = resolutions.get('R2')!;
    const r3 = resolutions.get('R3')!;
    const r4 = resolutions.get('R4')!;
    const r5 = resolutions.get('R5')!;

    console.log(`[Context IR] R_exclude Tokens: ${rEx.tokenCount} (Utility: ${rEx.utility})`);
    console.log(`[Context IR] R0 (Ref Pointer) Tokens: ${r0.tokenCount} (Utility: ${r0.utility})`);
    console.log(`[Context IR] R1 (Name Skeleton) Tokens: ${r1.tokenCount} (Utility: ${r1.utility})`);
    console.log(`[Context IR] R2 (API Contract) Tokens: ${r2.tokenCount} (Utility: ${r2.utility})`);
    console.log(`[Context IR] R3 (Callee Stubs) Tokens: ${r3.tokenCount} (Utility: ${r3.utility})`);
    console.log(`[Context IR] R4 (Sliced Body) Tokens: ${r4.tokenCount} (Utility: ${r4.utility})`);
    console.log(`[Context IR] R5 (Full Verbatim) Tokens: ${r5.tokenCount} (Utility: ${r5.utility})`);

    if (rEx.tokenCount !== 0 || rEx.utility !== 0) {
        throw new Error('R_exclude must produce exactly 0 tokens and 0 utility');
    }

    if (r0.tokenCount >= r2.tokenCount || r2.tokenCount >= r5.tokenCount) {
        throw new Error('Resolution token costs must increase monotonically from R0 to R5');
    }

    if (r0.utility >= r2.utility || r2.utility >= r5.utility) {
        throw new Error('Resolution utility scores must increase monotonically from R0 to R5');
    }

    console.log('✓ Context IR multi-resolution state machine verified.');

    // 2. Test Source Provenance Engine
    const provenance = new SourceProvenanceEngine(process.cwd());

    const generatedOpenApiCode = `
/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech).
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
export class PetstoreClient {
  public async getPetById(id: number) { /* 1000 lines of generated HTTP code */ }
}
`;

    const normalUserCode = `
export class OrderService {
  public calculateTotal(items: Item[]): number {
    return items.reduce((sum, i) => sum + i.price, 0);
  }
}
`;

    const generatedMatch = provenance.inspectProvenance('src/api/petstore.generated.ts', generatedOpenApiCode);
    const normalMatch = provenance.inspectProvenance('src/services/orderService.ts', normalUserCode);

    if (!generatedMatch.isGenerated || generatedMatch.generatorType !== 'openapi') {
        throw new Error(`Failed to detect OpenAPI generated source code (Got: ${JSON.stringify(generatedMatch)})`);
    }

    if (normalMatch.isGenerated) {
        throw new Error('Incorrectly flagged normal handwritten code as generated');
    }

    console.log(`[Provenance] Detected ${generatedMatch.generatorType} code artifact: ${generatedMatch.originalFileTokens} tokens`);
    console.log('✓ Source Provenance Engine verified.');

    return true;
}
