/**
 * Phase 14 Automated Test Suite: Terminal Optimization & Source Provenance
 * 
 * Verifies:
 * 1. Permitted source authorization and consent enforcement.
 * 2. ANSI, control sequence, carriage-return progress overwrites, and line length bounding.
 * 3. Secret, credential, home directory, and IP/URL sanitization.
 * 4. Failure clustering, exact error codes, first/last causal frames, and reversible hash pointer.
 * 5. Typed provenance classification (authoritative, generated, vendored, spec, migration, minified, external).
 * 6. Snapshot-safe specification resolution (without raw disk I/O).
 * 7. Low-trust artifact displacement protection in candidate ranking.
 * 8. Causal frame source attribution linking terminal errors to workspace snapshot files.
 * 9. PipelineOrchestrator integration and ComponentReceiptTrail auditing.
 */

import * as assert from 'assert';
import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import { AstPrunerEngine } from '../src/ast/pruner';
import { VersionedWorkspaceIndex } from '../src/workspace/workspaceIndex';
import { TerminalOutputOptimizer } from '../src/workspace/terminalOptimizer';
import { SourceProvenanceEngine } from '../src/workspace/provenance';
import { WorkspaceSignalCoordinator } from '../src/workspace/signalCoordinator';
import { WorkspaceSignalSnapshot } from '../src/workspace/signalTypes';
import { EvidenceAwareRetriever } from '../src/retrieval/evidenceRetriever';
import { PipelineOrchestrator } from '../src/engine/pipelineOrchestrator';
import { FeatureFlagRegistry } from '../src/engine/featureFlags';

export async function runPhase14TerminalProvenanceTests(): Promise<void> {
    console.log('\n--- Running Phase 14 Terminal Optimization & Source Provenance Tests ---');

    // Setup temporary workspace
    const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'tokonomics-phase14-'));
    const srcDir = path.join(tempDir, 'src');
    const vendorDir = path.join(tempDir, 'vendor');
    const protoDir = path.join(tempDir, 'proto');
    fs.mkdirSync(srcDir, { recursive: true });
    fs.mkdirSync(vendorDir, { recursive: true });
    fs.mkdirSync(protoDir, { recursive: true });

    const authFile = path.join(srcDir, 'authService.ts');
    const generatedFile = path.join(srcDir, 'user_pb.generated.ts');
    const specFile = path.join(protoDir, 'user.proto');
    const vendorFile = path.join(vendorDir, 'helper.ts');

    fs.writeFileSync(authFile, [
        'export class AuthService {',
        '  public login(user: string, token: string): boolean {',
        '    if (!token) throw new Error("Invalid token");',
        '    return true;',
        '  }',
        '}'
    ].join('\n'));

    fs.writeFileSync(generatedFile, [
        '/**',
        ' * Generated by protoc. DO NOT EDIT.',
        ' */',
        'export class UserMessage {',
        '  public id: string = "";',
        '}'
    ].join('\n'));

    fs.writeFileSync(specFile, [
        'syntax = "proto3";',
        'message UserMessage {',
        '  string id = 1;',
        '}'
    ].join('\n'));

    fs.writeFileSync(vendorFile, [
        'export function thirdPartyHelper(): string {',
        '  return "vendored";',
        '}'
    ].join('\n'));

    const index = new VersionedWorkspaceIndex([tempDir], new AstPrunerEngine());
    const snapshot = await index.initialize();
    assert.ok(snapshot.files.size >= 3, 'Snapshot must index created workspace files');

    // 1. Permitted Terminal Sources & Authorization Enforcement
    {
        const terminal = new TerminalOutputOptimizer();

        // 1a. Unauthorized source must be rejected fail-closed
        const unauthorizedRes = terminal.parseTerminalOutput('Error: build failure', {
            source: 'unauthorized',
            userConsented: true
        });
        assert.strictEqual(unauthorizedRes.isAuthorized, false, 'Unauthorized source must be rejected');
        assert.strictEqual(unauthorizedRes.totalErrors, 0, 'Zero errors parsed on unauthorized source');
        assert.strictEqual(unauthorizedRes.compactDiagnosticContext, '', 'No diagnostic context on unauthorized source');

        // 1b. Missing consent must be rejected fail-closed
        const noConsentRes = terminal.parseTerminalOutput('Error: build failure', {
            source: 'consented_shell',
            userConsented: false
        });
        assert.strictEqual(noConsentRes.isAuthorized, false, 'Unconsented source must be rejected');
        assert.strictEqual(noConsentRes.rejectionReason, 'unauthorized_or_no_consent');

        // 1c. Authorized source proceeds
        const authorizedRes = terminal.parseTerminalOutput('npm ERR! code ELIFECYCLE', {
            source: 'user_selection',
            userConsented: true
        });
        assert.strictEqual(authorizedRes.isAuthorized, true, 'Authorized user selection must be processed');
        console.log('✓ Permitted terminal source authorization and consent gates verified.');
    }

    // 2. ANSI, Control Codes, Carriage-Return Progress & Oversized Lines Normalization
    {
        const terminal = new TerminalOutputOptimizer();

        // Progress bar overwrite using \r
        const rawProgressOutput = [
            'Compiling assets...',
            '[====>     ] 30%\r[========> ] 60%\rFinished asset build in 1.2s',
            '\u001b[31;1mError: TS2339 in \u0007' + authFile + ':3:15\u001b[0m',
            'Property "token" does not exist'
        ].join('\n');

        const normalized = terminal.normalizeTerminalText(rawProgressOutput);
        assert.ok(!normalized.includes('\u001b'), 'ANSI sequences must be stripped');
        assert.ok(!normalized.includes('\u0007'), 'ASCII control characters must be stripped');
        assert.ok(!normalized.includes('[====>'), 'Overwritten progress bar chunk must be stripped');
        assert.ok(normalized.includes('Finished asset build'), 'Resolved carriage return chunk must be retained');
        assert.ok(normalized.includes('TS2339'), 'Error line must be preserved');

        // Oversized line truncation
        const hugeLine = 'x'.repeat(5000);
        const capped = terminal.normalizeTerminalText(hugeLine);
        assert.ok(capped.length <= 2000, 'Oversized lines must be capped at 2,000 characters');

        console.log('✓ ANSI, control character, carriage-return progress, and line length bounding verified.');
    }

    // 3. Secret, Credential, Home Path, and IP/URL Redaction
    {
        const terminal = new TerminalOutputOptimizer();
        const mockApiKey = ['sk', 'test', 'supersecrettoken1234567890'].join('_');
        const rawWithSecrets = [
            'FAIL tests/auth.test.ts',
            '  ✕ login should succeed (50ms)',
            '    Authentication failed using api_key=' + mockApiKey + ' at /home/developer/workspace/auth.ts:10',
            '    Connecting to internal database at 192.168.1.105 with remote https://user:pass@github.com/corp/repo.git',
            '    at Object.login (' + authFile + ':3:10)'
        ].join('\n');

        const cluster = terminal.parseTerminalOutput(rawWithSecrets, { source: 'user_selection', userConsented: true });
        assert.ok(!cluster.compactDiagnosticContext.includes(mockApiKey), 'API key must be redacted');
        assert.ok(!cluster.compactDiagnosticContext.includes('/home/developer'), 'Home directory must be scrubbed');
        assert.ok(cluster.compactDiagnosticContext.includes('<HOME_DIR>'), 'Home directory replacement tag present');
        assert.ok(!cluster.compactDiagnosticContext.includes('192.168.1.105'), 'Private IP must be scrubbed');
        assert.ok(!cluster.compactDiagnosticContext.includes('https://user:pass@github.com'), 'Remote URL must be scrubbed');
        assert.ok(cluster.compactDiagnosticContext.includes('<REDACTED_URL>'), 'URL replacement tag present');

        console.log('✓ Secret, credential, home path, and IP/URL redaction verified.');
    }

    // 4. Failure Clustering, Exact Error Codes, Causal Frames & Reversible Pointer
    {
        const terminal = new TerminalOutputOptimizer();
        const tscOutput = [
            'src/authService.ts:3:15 - error TS2339: Property "validate" does not exist on type "UserModel".',
            '',
            '3     return this.users.validate(username, token);',
            '                        ~~~~~~~~',
            '',
            'Found 1 error in src/authService.ts:3'
        ].join('\n');

        const cluster = terminal.parseTerminalOutput(tscOutput);
        assert.strictEqual(cluster.tool, 'typescript_tsc');
        assert.ok(cluster.errorCodes?.includes('TS2339'), 'Must extract exact TS2339 error code');
        assert.ok(cluster.sourcePointer?.startsWith('term:sha256:'), 'Must generate reversible hash pointer');
        assert.ok(!cluster.sourcePointer?.includes(tscOutput), 'Source pointer must not contain raw text');

        // Multi-frame stack trace with node_modules frame and user code frame
        const stackTraceOutput = [
            'Error: Connection refused',
            '    at Socket.emit (node_modules/express/socket.js:50:10)',
            '    at AuthService.login (' + authFile + ':3:5)',
            '    at Object.execute (src/index.ts:12:1)'
        ].join('\n');

        const stackCluster = terminal.parseTerminalOutput(stackTraceOutput);
        assert.ok(stackCluster.firstCausalFrame, 'Must extract first causal frame');
        // First causal frame should skip node_modules and isolate AuthService.login
        assert.strictEqual(stackCluster.firstCausalFrame?.functionName, 'AuthService.login');
        assert.strictEqual(stackCluster.firstCausalFrame?.isUserCode, true);
        assert.strictEqual(stackCluster.lastCausalFrame?.functionName, 'Object.execute');

        console.log('✓ Failure clustering, error code extraction, causal frames, and hash pointers verified.');
    }

    // 5. Typed Source Provenance Classifications & Sensitivity Risk
    {
        const provenance = new SourceProvenanceEngine(tempDir);

        // 5a. Authoritative first-party code
        const authProv = provenance.inspectProvenance(authFile, fs.readFileSync(authFile, 'utf8'), snapshot);
        assert.strictEqual(authProv.category, 'authoritative_source');
        assert.strictEqual(authProv.isLowTrust, false);
        assert.strictEqual(authProv.sensitivityRisk, 'none');

        // 5b. Generated code
        const genProv = provenance.inspectProvenance(generatedFile, fs.readFileSync(generatedFile, 'utf8'), snapshot);
        assert.strictEqual(genProv.category, 'generated');
        assert.strictEqual(genProv.isLowTrust, true);
        assert.strictEqual(genProv.generatorType, 'protobuf');

        // 5c. Vendored code
        const vendorProv = provenance.inspectProvenance(vendorFile, fs.readFileSync(vendorFile, 'utf8'), snapshot);
        assert.strictEqual(vendorProv.category, 'vendored');
        assert.strictEqual(vendorProv.isLowTrust, true);

        // 5d. Specification file
        const specProv = provenance.inspectProvenance(specFile, fs.readFileSync(specFile, 'utf8'), snapshot);
        assert.strictEqual(specProv.category, 'specification');
        assert.strictEqual(specProv.isLowTrust, false);

        // 5e. Migration file
        const migrationProv = provenance.inspectProvenance('src/migrations/001_initial_schema.sql', 'CREATE TABLE users (id INT);', snapshot);
        assert.strictEqual(migrationProv.category, 'migration');
        assert.strictEqual(migrationProv.sensitivityRisk, 'high');

        const outsideProv = provenance.inspectProvenance(path.join(path.dirname(tempDir), 'outside.ts'), 'export const outside = true;', snapshot);
        assert.strictEqual(outsideProv.category, 'external', 'Absolute files outside the workspace must remain external');

        // 5f. Minified file
        const minifiedProv = provenance.inspectProvenance('dist/bundle.min.js', 'function a(){return 1;}', snapshot);
        assert.strictEqual(minifiedProv.category, 'minified');
        assert.strictEqual(minifiedProv.isLowTrust, true);

        // 5g. Critical secret file
        const secretProv = provenance.inspectProvenance('.env.production', 'DATABASE_PASSWORD=SuperSecretPass', snapshot);
        assert.strictEqual(secretProv.sensitivityRisk, 'critical');

        console.log('✓ Typed provenance classifications across all 7 categories and sensitivity ratings verified.');
    }

    // 6. Snapshot-Safe Specification Matching (Zero Raw Disk I/O)
    {
        const provenance = new SourceProvenanceEngine(tempDir);
        // Spec resolution using immutable snapshot
        const specMatch = provenance.findMatchingSpecFile(generatedFile, 'protobuf', snapshot);
        assert.ok(specMatch !== null, 'Must find matching spec file in snapshot');
        assert.ok(specMatch?.specPath.includes('user.proto'), 'Matched spec path must be user.proto');
        assert.ok(specMatch?.content.includes('message UserMessage'), 'Must read spec content from snapshot file record');

        console.log('✓ Snapshot-safe specification resolution without disk I/O verified.');
    }

    // 7. Low-Trust Artifact Displacement Protection in Evidence Retrieval
    {
        const retriever = new EvidenceAwareRetriever();

        // 7a. Normal query not targeting generated or vendored code
        const genericRes = retriever.retrieve({
            query: 'Fix authentication login issue',
            taskType: 'debug',
            snapshot,
            activeFilePath: authFile
        });

        const selectedPaths = genericRes.selected.map(c => c.filePath);
        // Authoritative authService must be prioritized
        assert.ok(selectedPaths.some(p => p?.includes('authService.ts')), 'Authoritative source must be selected');

        // Generated and vendored candidates must carry provenance tags
        const allCandidateTags = genericRes.allCandidates.flatMap(c => c.provenance);
        assert.ok(allCandidateTags.some(t => t.startsWith('provenance:')), 'Candidates must carry provenance tags');
        assert.ok(allCandidateTags.some(t => t.startsWith('risk:')), 'Candidates must carry risk tags');

        // 7b. Query explicitly targeting protobuf generated symbol
        const targetedRes = retriever.retrieve({
            query: 'Inspect UserMessage protobuf struct',
            taskType: 'explanation',
            snapshot
        });

        // Targeted query should allow the generated file when explicitly asked
        const targetedPaths = targetedRes.selected.map(c => c.filePath);
        assert.ok(targetedPaths.some(p => p?.includes('user_pb.generated.ts')), 'Explicitly targeted generated code allowed');

        console.log('✓ Low-trust artifact displacement protection and query targeting verified.');
    }

    // 8. Causal Frame Source Attribution Linking Terminal to Workspace
    {
        const coordinator = new WorkspaceSignalCoordinator();

        const terminalContext = {
            source: 'user_selection' as const,
            userConsented: true,
            rawText: [
                'FAIL tests/auth.test.ts',
                '  ✕ login throws Invalid token',
                '    at AuthService.login (' + authFile + ':3:10)',
                '    at Object.testRun (tests/auth.test.ts:20:5)'
            ].join('\n'),
            capturedAt: Date.now()
        };

        const signalRes = coordinator.coordinateSignals({
            snapshot,
            signals: {
                snapshotGeneration: snapshot.generation,
                capturedAt: Date.now(),
                terminalContext
            },
            activeFilePath: authFile,
            flags: {
                enableTerminalOptimizer: true
            }
        });

        assert.ok(signalRes.terminalSignals.length >= 2, 'Must produce terminal failure summary and causal frame signals');
        const frameSignal = signalRes.terminalSignals.find(s => s.lineStart !== undefined && s.filePath?.includes('authService.ts'));
        assert.ok(frameSignal, 'Causal frame must be attributed to matching snapshot file authService.ts');
        assert.strictEqual(frameSignal?.lineStart, 3, 'Causal frame line number must be preserved');
        assert.strictEqual(frameSignal?.symbolName, 'AuthService.login');

        console.log('✓ Causal frame source attribution linking terminal error to snapshot verified.');
    }

    // 9. PipelineOrchestrator Integration & Receipt Trail Auditing
    {
        FeatureFlagRegistry.resetToDefault();
        const orchestrator = new PipelineOrchestrator();
        FeatureFlagRegistry.setFlag('enableTerminalOptimizer', true);
        FeatureFlagRegistry.setFlag('enableProvenance', true);

        const prompt = 'Fix authentication error';
        const res = await orchestrator.compileContext({
            messages: [{ role: 'user', content: prompt }],
            workspaceSnapshot: snapshot,
            activeFilePath: authFile,
            cursorLine: 3,
            allowWorkspaceRetrieval: true,
            signalSnapshot: {
                snapshotGeneration: snapshot.generation,
                capturedAt: Date.now(),
                terminalContext: {
                    source: 'user_selection',
                    userConsented: true,
                    rawText: 'error TS2339 in ' + authFile + ':3:15',
                    capturedAt: Date.now()
                }
            }
        });

        const receipts = res.receipts || [];
        assert.ok(receipts.length > 0, 'Receipts must be recorded');

        // Verify terminal_optimizer receipts
        const termAttempted = receipts.find(r => r.componentId === 'terminal_optimizer' && r.outcome === 'attempted');
        const termInvoked = receipts.find(r => r.componentId === 'terminal_optimizer' && r.outcome === 'invoked');
        const termTerminal = receipts.find(r => r.componentId === 'terminal_optimizer' && (r.outcome === 'contributed' || r.outcome === 'fallback'));

        assert.ok(termAttempted, 'terminal_optimizer must be attempted');
        assert.ok(termInvoked, 'terminal_optimizer must be invoked');
        assert.ok(termTerminal, 'Terminal evidence must report admitted contribution or a coded fallback.');

        // Verify source_provenance receipts
        const provAttempted = receipts.find(r => r.componentId === 'source_provenance' && r.outcome === 'attempted');
        const provInvoked = receipts.find(r => r.componentId === 'source_provenance' && r.outcome === 'invoked');
        const provTerminal = receipts.find(r => r.componentId === 'source_provenance' && (r.outcome === 'contributed' || r.outcome === 'fallback'));

        assert.ok(provAttempted, 'source_provenance must be attempted');
        assert.ok(provInvoked, 'source_provenance must be invoked');
        assert.ok(provTerminal, 'Provenance must be derived from admitted blocks or report a coded fallback.');

        // Reset flags
        FeatureFlagRegistry.resetToDefault();
        console.log('✓ PipelineOrchestrator integration and ComponentReceiptTrail receipts verified.');
    }

    console.log('\n====================================================================================');
    console.log('🎉 ALL PHASE 14 TERMINAL OPTIMIZATION & SOURCE PROVENANCE TESTS PASSED (100%)');
    console.log('====================================================================================\n');
}
