import * as path from 'path';
import * as fs from 'fs';
import { WorkspaceSnapshot } from './workspaceIndex';
import { SecuritySanitizer } from '../security/sanitizer';

export type ProvenanceCategory =
    | 'authoritative_source'
    | 'generated'
    | 'vendored'
    | 'specification'
    | 'migration'
    | 'minified'
    | 'external'
    | 'unknown';

export type SensitivityRisk = 'none' | 'low' | 'high' | 'critical';

export interface TypedProvenanceResult {
    readonly filePath: string;
    readonly category: ProvenanceCategory;
    readonly sensitivityRisk: SensitivityRisk;
    readonly generatorType?: 'openapi' | 'protobuf' | 'graphql' | 'grpc' | 'generic';
    readonly specFilePath?: string;
    readonly specContent?: string;
    readonly isLowTrust: boolean;
    readonly confidence: number;
    readonly reasons: readonly string[];
    readonly originalFileTokens: number;
    readonly specTokens: number;
    readonly estimatedSavingsPercent: number;
}

export interface ProvenanceMatch extends TypedProvenanceResult {
    readonly isGenerated: boolean;
}

export class SourceProvenanceEngine {
    private static readonly GENERATED_HEADER_PATTERNS = [
        /code generated by .* do not edit/i,
        /@generated/i,
        /generated by openapi generator/i,
        /generated by protoc/i,
        /this file is automatically generated/i,
        /autogenerated by swagger/i,
        /generated by graphql-codegen/i
    ];

    private static readonly GENERATED_FILE_EXTENSIONS = [
        /\.generated\.(ts|js|go|java|cs)$/i,
        /_pb\.(ts|js|go|py)$/i,
        /\.pb\.(go|ts|js)$/i,
        /_grpc\.(ts|js|go|py)$/i
    ];

    constructor(private workspaceRoot?: string) {}

    /**
     * Inspects a file's content and path to determine its typed provenance and sensitivity
     */
    public inspectProvenance(filePath: string, fileContent: string, snapshot?: WorkspaceSnapshot): ProvenanceMatch {
        const normalizedPath = filePath.replace(/\\/g, '/');
        const fileName = path.basename(filePath);
        const reasons: string[] = [];
        let category: ProvenanceCategory = 'authoritative_source';
        let generatorType: 'openapi' | 'protobuf' | 'graphql' | 'grpc' | 'generic' | undefined = undefined;
        let isLowTrust = false;
        let confidence = 0.9;

        // 1. Check for external/virtual files
        if (filePath.startsWith('untitled:') || filePath.startsWith('vscode-userdata:') || normalizedPath.includes('/temp/') || normalizedPath.includes('/tmp/')) {
            category = 'external';
            isLowTrust = true;
            reasons.push('Virtual or temporary path outside normal workspace tree');
        } else if (this.workspaceRoot && path.isAbsolute(filePath)) {
            const rel = path.relative(this.workspaceRoot, filePath);
            if (rel.startsWith('..') || path.isAbsolute(rel)) {
                category = 'external';
                isLowTrust = true;
                reasons.push('Path outside workspace root containment boundary');
            }
        }

        // 2. Check for vendored / third-party code
        if (category === 'authoritative_source') {
            if (/(?:^|[\\/])(vendor|third_party|node_modules|extern|deps|bower_components)[\\/]/i.test(normalizedPath)) {
                category = 'vendored';
                isLowTrust = true;
                confidence = 0.95;
                reasons.push('Matched vendored/third-party directory pattern');
            }
        }

        // 3. Check for specification files
        if (category === 'authoritative_source') {
            const isProto = /\.(?:proto|graphql|gql)$/i.test(fileName);
            const isSchema = /\.(?:json|ya?ml)$/i.test(fileName) && /(?:swagger|openapi|schema|spec)/i.test(fileName);
            if (isProto || isSchema) {
                category = 'specification';
                isLowTrust = false;
                confidence = 0.95;
                reasons.push('Matched interface or schema specification file signature');
            }
        }

        // 4. Check for database / schema migrations
        if (category === 'authoritative_source') {
            if (/(?:^|[\\/])migrations?[\\/]|(?:^|[\\/])db[\\/]migrate[\\/]|\bmigration\b.*\.(?:sql|ts|js|py)$/i.test(normalizedPath)) {
                category = 'migration';
                isLowTrust = false;
                confidence = 0.9;
                reasons.push('Matched database or state migration script pattern');
            }
        }

        // 5. Check for minified files
        if (category === 'authoritative_source') {
            const isMinName = /\.min\.(?:js|css|json)$/i.test(fileName);
            const lines = fileContent.split('\n');
            const lineCount = lines.length;
            const avgLineLen = fileContent.length / Math.max(1, lineCount);
            if (isMinName || (lineCount <= 3 && fileContent.length > 1000 && avgLineLen > 300)) {
                category = 'minified';
                isLowTrust = true;
                confidence = 0.95;
                reasons.push('Matched minified artifact signature or dense character density');
            }
        }

        // 6. Check for generated code artifacts
        let isGenerated = false;
        if (category === 'authoritative_source' || category === 'vendored') {
            for (const pattern of SourceProvenanceEngine.GENERATED_FILE_EXTENSIONS) {
                if (pattern.test(fileName)) {
                    isGenerated = true;
                    category = 'generated';
                    isLowTrust = true;
                    reasons.push(`Matched generated file naming convention: ${pattern.toString()}`);
                    if (fileName.includes('_pb') || fileName.includes('.pb.')) generatorType = 'protobuf';
                    if (fileName.includes('_grpc')) generatorType = 'grpc';
                    break;
                }
            }

            const topLines = fileContent.split('\n').slice(0, 15).join('\n');
            for (const pattern of SourceProvenanceEngine.GENERATED_HEADER_PATTERNS) {
                if (pattern.test(topLines)) {
                    isGenerated = true;
                    category = 'generated';
                    isLowTrust = true;
                    reasons.push(`Matched generated code header comment: ${pattern.toString()}`);
                    if (/openapi/i.test(topLines) || /swagger/i.test(topLines)) generatorType = 'openapi';
                    else if (/protobuf|protoc/i.test(topLines)) generatorType = 'protobuf';
                    else if (/graphql/i.test(topLines)) generatorType = 'graphql';
                    else if (/grpc/i.test(topLines)) generatorType = 'grpc';
                    else if (!generatorType) generatorType = 'generic';
                    break;
                }
            }
        }

        // 7. Sensitivity Risk Assessment
        let sensitivityRisk: SensitivityRisk = 'none';
        if (/\.env(?:$|\.)|\.pem$|\.key$|id_rsa/i.test(fileName) || SecuritySanitizer.containsSecret(fileContent)) {
            sensitivityRisk = 'critical';
            reasons.push('Detected secrets or cryptographic keys');
        } else if (category === 'migration') {
            sensitivityRisk = 'high';
            reasons.push('Database migration contains persistent schema mutation risk');
        } else if (category === 'vendored' || category === 'external') {
            sensitivityRisk = 'low';
        }

        // 8. Find matching spec file if generated
        let specMatch: { specPath: string; content: string } | null = null;
        if (isGenerated && generatorType) {
            specMatch = this.findMatchingSpecFile(filePath, generatorType, snapshot);
        }

        const originalFileTokens = Math.round(fileContent.length / 4);
        const specTokens = specMatch ? Math.round(specMatch.content.length / 4) : 0;
        const estimatedSavingsPercent = specMatch ? 85 : 0;

        return {
            filePath,
            category,
            isGenerated,
            generatorType,
            specFilePath: specMatch?.specPath,
            specContent: specMatch?.content,
            originalFileTokens,
            specTokens,
            estimatedSavingsPercent,
            sensitivityRisk,
            isLowTrust,
            confidence,
            reasons
        };
    }

    /**
     * Finds matching specification file in snapshot or workspace root
     */
    public findMatchingSpecFile(
        generatedFilePath: string,
        type: 'openapi' | 'protobuf' | 'graphql' | 'grpc' | 'generic',
        snapshot?: WorkspaceSnapshot
    ): { specPath: string; content: string } | null {
        const candidateExts = type === 'protobuf' || type === 'grpc' 
            ? ['.proto'] 
            : type === 'graphql' 
                ? ['.graphql', '.gql'] 
                : ['.yaml', '.yml', '.json'];

        const baseName = path.basename(generatedFilePath).split('.')[0].replace(/_pb|_grpc|generated/g, '').toLowerCase();

        // Fast snapshot lookup without disk I/O
        if (snapshot) {
            for (const record of snapshot.files.values()) {
                const ext = path.extname(record.relativePath).toLowerCase();
                if (candidateExts.includes(ext)) {
                    const normRel = record.relativePath.toLowerCase();
                    if (normRel.includes(baseName) || normRel.includes('openapi') || normRel.includes('schema') || normRel.includes('swagger')) {
                        return {
                            specPath: record.relativePath,
                            content: record.skeleton || ''
                        };
                    }
                }
            }
        }

        // Fallback to workspace disk scan
        if (!this.workspaceRoot || !fs.existsSync(this.workspaceRoot)) {
            return null;
        }

        try {
            const scanDir = (dir: string, depth: number = 0): { specPath: string; content: string } | null => {
                if (depth > 4) return null;
                const entries = fs.readdirSync(dir, { withFileTypes: true });
                for (const entry of entries) {
                    const fullPath = path.join(dir, entry.name);
                    if (entry.isDirectory()) {
                        if (!['node_modules', '.git', 'dist', 'out', '.gemini'].includes(entry.name)) {
                            const sub = scanDir(fullPath, depth + 1);
                            if (sub) return sub;
                        }
                    } else if (entry.isFile()) {
                        const ext = path.extname(entry.name).toLowerCase();
                        if (candidateExts.includes(ext)) {
                            const nameLower = entry.name.toLowerCase();
                            if (nameLower.includes(baseName) || nameLower.includes('openapi') || nameLower.includes('schema') || nameLower.includes('swagger')) {
                                return {
                                    specPath: path.relative(this.workspaceRoot!, fullPath).replace(/\\/g, '/'),
                                    content: fs.readFileSync(fullPath, 'utf8')
                                };
                            }
                        }
                    }
                }
                return null;
            };

            return scanDir(this.workspaceRoot);
        } catch {}

        return null;
    }
}
